export enum QualificationStatus {
  QUALIFIED = 'QUALIFIED',
  PARTIALLY_QUALIFIED = 'PARTIALLY_QUALIFIED',
  NOT_YET_QUALIFIED = 'NOT_YET_QUALIFIED',
  ELIGIBLE = 'QUALIFIED',
  CONDITIONAL = 'PARTIALLY_QUALIFIED',
  INELIGIBLE = 'NOT_YET_QUALIFIED',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  IN_REVIEW = 'IN_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  NEEDS_INFO = 'NEEDS_INFO',
}

export enum UserRole {
  APPLICANT = 'APPLICANT',
  CONSULTANT = 'CONSULTANT',
  ADMIN = 'ADMIN',
}
